osx_image: xcode11
language: swift

env:
  - PROJECT_NAME=ClaretCacheDemo

jobs:
  include:
    # - stage: Lint
    install:
      - wget --output-document /tmp/SwiftLint.pkg https://github.com/realm/SwiftLint/releases/download/0.33.1/SwiftLint.pkg && sudo installer -pkg /tmp/SwiftLint.pkg -target /
    script:
      - swiftlint --config configs/.swiftlint.yml
      - swift test
      - swift build
      - xcodebuild -workspace ${PROJECT_NAME}.xcworkspace -scheme ${PROJECT_NAME} -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.1' build
# stages:
# - Lint
# - Test
